### ISSUE TITLE
Fix variable with "incompatible types" being imported twice

### ISSUE THREAD

**Issue by karkhaz** [Ericsson/clang#13] opened 2016-10-14 00:34 UTC
I'm occasionally observing the following sort of error:

```
~/doc/fuchsia/magenta/third_party/lib/acpica/source/include/acpica/acpixf.h:284:37: error: external variable 'AcpiGbl_FADT' declared with incompatible types in different translation units ('ACPI_TABLE_FADT' (aka 'struct acpi_table_fadt') vs. 'ACPI_TABLE_FADT' (aka 'struct acpi_table_fadt'))
ACPI_GLOBAL (ACPI_TABLE_FADT,       AcpiGbl_FADT);
                                    ^
~/doc/fuchsia/magenta/third_party/lib/acpica/source/include/acpica/acpixf.h:284:37: note: declared here with type 'ACPI_TABLE_FADT' (aka 'struct acpi_table_fadt')
ACPI_GLOBAL (ACPI_TABLE_FADT,       AcpiGbl_FADT);
                                    ^
```

i.e., exactly the same variable is being imported twice (note that the two source files are the same), and then I get a complaint that the two types are incompatible (ACPI_TABLE_FADT vs. ACPI_TABLE_FADT).

Minimal test case pending.

**Comment by Xazax-hun** [comment] 2017-05-15 15:12
We fixed some related issues since then. Do you have time to try to reproduce this? If no, feel free to just close this issue.

**Closed** 2017-10-05 22:19 UTC
