### ISSUE TITLE
Assertion `Field->getInClassInitializer() && "initializer hasn't been parsed"' failed

### ISSUE THREAD

**Issue by balazske** [Ericsson/clang#429] opened 2018-07-16 13:20 UTC
```
#0 0x00007ff35e2b452a llvm::sys::PrintStackTrace(llvm::raw_ostream&) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/lib/Support/Unix/Signals.inc:402:0
#1 0x00007ff35e2b24ae llvm::sys::RunSignalHandlers() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/lib/Support/Signals.cpp:50:0
#2 0x00007ff35e2b25fc SignalHandler(int) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/lib/Support/Unix/Signals.inc:252:0
#3 0x00007ff35dc6b0c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x110c0)
#4 0x00007ff35c4a1fff gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x32fff)
#5 0x00007ff35c4a342a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3442a)
#6 0x00007ff35c49ae67 (/lib/x86_64-linux-gnu/libc.so.6+0x2be67)
#7 0x00007ff35c49af12 (/lib/x86_64-linux-gnu/libc.so.6+0x2bf12)
#8 0x00007ff3595f67d8 llvm::cast_retty<clang::CompoundLiteralExpr, clang::Stmt const*>::ret_type llvm::cast<clang::CompoundLiteralExpr, clang::Stmt const>(clang::Stmt const*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/include/llvm/Support/Casting.h:255:0
#9 0x00007ff3595f67d8 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1366:0
#10 0x00007ff3595f6b87 clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:567:0
#11 0x00007ff3595f6dcc clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:411:0
#12 0x00007ff3595c13bd clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:533:0
#13 0x00007ff3595c16db clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:282:0
#14 0x00007ff3595c17fe clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:216:0
#15 0x00007ff359cc0ae1 llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>::release() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:189:0
#16 0x00007ff359cc0ae1 llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>::~IntrusiveRefCntPtr() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:157:0
#17 0x00007ff359cc0ae1 clang::ento::ExprEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:114:0
#18 0x00007ff359cc0ae1 (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) [clone .part.4614] /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:721:0
#19 0x00007ff359cc1294 RunPathSensitiveChecks /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:741:0
#20 0x00007ff359cc1294 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:687:0
#21 0x00007ff359ccc9f8 llvm::DenseMapBase<llvm::DenseMap<clang::Decl const*, llvm::detail::DenseSetEmpty, llvm::DenseMapInfo<clang::Decl const*>, llvm::detail::DenseSetPair<clang::Decl const*> >, clang::Decl const*, llvm::detail::DenseSetEmpty, llvm::DenseMapInfo<clang::Decl const*>, llvm::detail::DenseSetPair<clang::Decl const*> >::begin() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/include/llvm/ADT/DenseMap.h:73:0
#22 0x00007ff359ccc9f8 llvm::detail::DenseSetImpl<clang::Decl const*, llvm::DenseMap<clang::Decl const*, llvm::detail::DenseSetEmpty, llvm::DenseMapInfo<clang::Decl const*>, llvm::detail::DenseSetPair<clang::Decl const*> >, llvm::DenseMapInfo<clang::Decl const*> >::begin() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/include/llvm/ADT/DenseSet.h:159:0
#23 0x00007ff359ccc9f8 HandleDeclsCallGraph /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:504:0
#24 0x00007ff359ccc9f8 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) [clone .part.4636] /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:552:0
#25 0x00007ff35d1a71f8 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp:310:0
#26 0x00007ff35ac0dd48 std::enable_if<std::__and_<std::is_move_constructible<bool>, std::is_move_assignable<bool> >::value, void>::type std::swap<bool>(bool&, bool&) /usr/include/c++/6/bits/move.h:192:0
#27 0x00007ff35ac0dd48 clang::ParseAST(clang::Sema&, bool, bool) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/Parse/ParseAST.cpp:161:0
#28 0x00007ff35d17fcce clang::FrontendAction::Execute() /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897:0
#29 0x00007ff35d1437f6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:992:0
#30 0x00007ff35d0ae872 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:252:0
#31 0x000055e024d81e78 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
#32 0x000055e024d7d3f0 ExecuteCC1Tool /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/tools/driver/driver.cpp:309:0
#33 0x000055e024d7d3f0 main /var/jenkins_home/workspace/build_clang_relwithdebinfo/llvm/tools/clang/tools/driver/driver.cpp:388:0
#34 0x00007ff35c48f2e1 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e1)
#35 0x000055e024d7e7ba _start (/var/jenkins_home/workspace/build_clang_relwithdebinfo/build/bin/clang-6.0+0xc7ba)
```

**Comment by balazske** [comment] 2018-07-16 13:36
The log file contains warnings "cannot import unsupported AST node CXXStdInitializerListExpr".
But the import of CXXStdInitializerListExpr was added already in #391 . Probably old code is used?
The assertion is related to not existing field initializer, this is likely related to missing CXXStdInitializerListExpr.

**Comment by martong** [comment] 2018-07-23 08:20
Duplicate of #440

**Closed as completed by martong** 2018-07-23 08:20 UTC
