### ISSUE TITLE
CURL: Assertion `isa(Val) && "cast() argument of incompatible type!"' failed

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#402] opened 2018-06-04 09:24 UTC
CTU has this assertion on CURL code

Assertion `isa(Val) && "cast() argument of incompatible type!"' failed
http://cc.elte.hu:15009/job/test-ctu-master-with-projects/HTML_Report/

**Comment by gerazo** [comment] 2018-06-12 14:30
On the newest curl code, it is not coming. I need to get access to this jenkins to further examine. @dkrupp

**Comment by Xazax-hun** [comment] 2018-06-13 09:00
You do have access, the whole Jenkins is running on CC. 

This is the Curl version that is being used (copied from the csa-testbench config):
```
    {
      "name": "Curl",
      "url": "https://github.com/curl/curl.git",
      "tag": "curl-7_59_0"
    },

```

**Comment by gerazo** [comment] 2018-06-13 15:30
We are not building this project the right way. cmake is not maintained for this. According to this https://github.com/curl/curl/blob/master/GIT-INFO we should do something like
```
{
      "name": "Curl",
      "url": "https://github.com/curl/curl.git",
      "tag": "curl-7_60_0"
      "configure_command": "./buildconf && ./configure"
    },
```
In fact, a normal curl build has around 180 compilation units while with this cmake version, we have around 600. So something is really screwed here.
How could I fix the above? Is there a repo to commit to @Xazax-hun ?

**Comment by gerazo** [comment] 2018-06-20 13:02
Ok, so no more asserts are there with the correct compilation. Jenkins was using an old version with a not supported build method. Moreover, it was building a different branch. I think, we can close this.

**Comment by Xazax-hun** [comment] 2018-06-20 14:12
This assert is there in other projects. Even if we cannot reproduce on Curl, I think there is a problem in the analyzer which should be fixed. FFMPEG is an example.

**Comment by Xazax-hun** [comment] 2018-06-20 19:28
Oh, I see, so it was using ctu-master. If it does not reproduce with ctu-clang6, even if it was using the old method of building, I think this is ok to close for now.

**Closed as completed by Xazax-hun** 2018-06-20 19:28 UTC

**Comment by gerazo** [comment] 2018-06-21 07:49
It is not reproduced even with the old method. Changing the method was just a side-effect. Anyway if you know that ffmpeg shows this, we have a shorter job with that which is probably more up-to-date. We should have a look.

**Comment by Xazax-hun** [comment] 2018-06-21 09:07
In the shorter job, with the ctu-clang6 branch, I also saw this assert on bitcoin: http://cc.inf.elte.hu:15009/job/test-clang-with-projects/HTML_Report/
