### ISSUE TITLE
VisitUsingShadowDecl related "already imported" assertion

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#323] opened 2018-03-06 09:20 UTC
```
clang-5.0: ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7433: virtual clang::Decl *clang::ASTImporter::Imported(clang::Decl *, clang::Decl *): Assertion `(Pos == ImportedDecls.end() || Pos->second == To) && "Try to import an already imported Decl"' failed.
#0 0x00007f4eb842a0b9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:398:11
#1 0x00007f4eb842a269 PrintStackTraceSignalHandler(void*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:462:1
#2 0x00007f4eb84288c3 llvm::sys::RunSignalHandlers() /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Signals.cpp:0:5
#3 0x00007f4eb842a5c4 SignalHandler(int) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:252:1
#4 0x00007f4eb7699390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#5 0x00007f4eb4aac428 gsignal /build/glibc-Cl5G7W/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#6 0x00007f4eb4aae02a abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:91:0
#7 0x00007f4eb4aa4bd7 __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92:0
#8 0x00007f4eb4aa4c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#9 0x00007f4eb11c4134 clang::ASTImporter::Imported(clang::Decl*, clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7435:7
#10 0x00007f4eb11ae244 clang::ASTNodeImporter::VisitUsingShadowDecl(clang::UsingShadowDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:3511:7
#11 0x00007f4eb11d44f4 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:341:1
#12 0x00007f4eb119a222 clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:7
#13 0x00007f4eb11b89f5 clang::ASTNodeImporter::VisitDeclRefExpr(clang::DeclRefExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5235:14
#14 0x00007f4eb11d5fff clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:477:1
#15 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#16 0x00007f4eb1199915 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6888:10
#17 0x00007f4eb11bbf65 clang::ASTNodeImporter::VisitImplicitCastExpr(clang::ImplicitCastExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5689:9
#18 0x00007f4eb11d5f3b clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:423:1
#19 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#20 0x00007f4eb1199915 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6888:10
#21 0x00007f4eb11c1a61 clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6438:9
#22 0x00007f4eb11d5deb clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:329:1
#23 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#24 0x00007f4eb1199915 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6888:10
#25 0x00007f4eb11bbf65 clang::ASTNodeImporter::VisitImplicitCastExpr(clang::ImplicitCastExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5689:9
#26 0x00007f4eb11d5f3b clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:423:1
#27 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#28 0x00007f4eb1199915 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6888:10
#29 0x00007f4eb11bc0fe clang::ASTNodeImporter::VisitExplicitCastExpr(clang::ExplicitCastExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5706:9
#30 0x00007f4eb11ee388 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitCStyleCastExpr(clang::CStyleCastExpr*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:369:1
#31 0x00007f4eb11d5e77 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:369:1
#32 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#33 0x00007f4eb1199915 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6888:10
#34 0x00007f4eb11baac8 clang::ASTNodeImporter::VisitBinaryOperator(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5513:9
#35 0x00007f4eb11edc68 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitBinAssign(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:133:3
#36 0x00007f4eb11d5517 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:69:26
#37 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#38 0x00007f4eb11e74a7 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:347:36
#39 0x00007f4eb11e744a clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#40 0x00007f4eb11e73b0 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:353:14
#41 0x00007f4eb11ca95c bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:359:7
#42 0x00007f4eb11b579c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4753:7
#43 0x00007f4eb11d5972 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#44 0x00007f4eb11a2c03 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6902:9
#45 0x00007f4eb11a7571 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2563:15
#46 0x00007f4eb11a7e0d clang::ASTNodeImporter::VisitCXXMethodDecl(clang::CXXMethodDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2589:3
#47 0x00007f4eb11d45d4 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:399:1
#48 0x00007f4eb119a222 clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:7
#49 0x00007f4eb119e7c7 clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool, clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1070:38
#50 0x00007f4eb11a1186 clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1673:10
#51 0x00007f4eb11d41c8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:105:1
#52 0x00007f4eb119a222 clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:7
#53 0x00007f4eb119ca6e clang::ASTImporter::ImportContext(clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6833:23
#54 0x00007f4eb119c8e2 clang::ASTNodeImporter::ImportDeclParts(clang::NamedDecl*, clang::DeclContext*&, clang::DeclContext*&, clang::DeclarationName&, clang::NamedDecl*&, clang::SourceLocation&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:982:5
#55 0x00007f4eb11a5b5c clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2343:7
#56 0x00007f4eb11a7e0d clang::ASTNodeImporter::VisitCXXMethodDecl(clang::CXXMethodDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2589:3
#57 0x00007f4eb11d45d4 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:399:1
#58 0x00007f4eb119a222 clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:7
#59 0x00007f4eaa40d7f2 clang::tooling::CrossTranslationUnit::getCrossTUDefinition(clang::FunctionDecl const*, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/Tooling/CrossTranslationUnit.cpp:263:20
#60 0x00007f4eaa8760af clang::ento::AnyFunctionCall::getRuntimeDefinition() const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CallEvent.cpp:384:37
#61 0x00007f4eaa90e276 clang::ento::ExprEngine::defaultEvalCall(clang::ento::NodeBuilder&, clang::ento::ExplodedNode*, clang::ento::CallEvent const&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:915:34
#62 0x00007f4eaa88fdef clang::ento::CheckerManager::runCheckersForEvalCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::ento::CallEvent const&, clang::ento::ExprEngine&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:619:11
#63 0x00007f4eaa90d0a9 clang::ento::ExprEngine::evalCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNode*, clang::ento::CallEvent const&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:521:3
#64 0x00007f4eaa90cf6b clang::ento::ExprEngine::VisitCallExpr(clang::CallExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:0:5
#65 0x00007f4eaa8cd7e4 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1232:7
#66 0x00007f4eaa8ca964 clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:547:5
#67 0x00007f4eaa8ca62a clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:394:7
#68 0x00007f4eaa8aede6 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:532:1
#69 0x00007f4eaa8ae6e3 clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:281:1
#70 0x00007f4eaa8ae278 clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:216:3
#71 0x00007f4eac3cfcd5 clang::ento::ExprEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:114:19
#72 0x00007f4eac372bfb (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:726:7
#73 0x00007f4eac372991 (anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks(clang::Decl*, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:747:5
#74 0x00007f4eac372645 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:694:15
#75 0x00007f4eac365daa (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph(unsigned int) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:506:5
#76 0x00007f4eac36400d (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:561:5
#77 0x00007f4eaf466796 clang::ParseAST(clang::Sema&, bool, bool) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/Parse/ParseAST.cpp:159:13
#78 0x00007f4eb5bba4ec clang::ASTFrontendAction::ExecuteAction() /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:1005:1
#79 0x00007f4eb5bb9f60 clang::FrontendAction::Execute() /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:906:7
#80 0x00007f4eb5b330ba clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:981:7
#81 0x00007f4eb56fdcdf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:251:8
#82 0x0000000000426659 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/tools/driver/cc1_main.cpp:221:11
#83 0x00000000004194c9 ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/tools/driver/driver.cpp:306:5
#84 0x0000000000418100 main /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/tools/driver/driver.cpp:387:5
#85 0x00007f4eb4a97830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#86 0x00000000004170e9 _start (/home/egbomrt/WORK/llvm/build/debug/bin/clang-5.0+0x4170e9)
```

**Comment by dkrupp** [comment] 2018-03-19 10:53
duplicate of #333

**Closed by dkrupp** 2018-03-19 10:53 UTC
Labels: ASTImporter
